# This is the Dockerfile for preparing pre-trained models for inference.
# FROM python:3.8-slim
FROM python:3.8

WORKDIR /workspace
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt